import type { SiteLocale } from "@/lib/i18n";

export const salesCopy = {
  en: {
    title: "Get Your ClickBaitPays Replicated Site",
    description: "Grow your ClickBaitPays opportunity with a personalized replicated site featuring your referral link, videos, resources, and marketing materials.",
    ogTitle: "Your ClickBaitPays replicated site—ready to grow with you.",
    ogDescription: "A custom, ready-to-share site with your referral link and high-impact ClickBaitPays marketing materials.",
    twitterTitle: "Get your ClickBaitPays replicated site.", twitterDescription: "Your custom CBP growth hub—personalized and ready to share.",
    ogImage: "/og-personal-cbp-sites-v4.png", ogWidth: 1659, ogHeight: 948, ogLocale: "en_US",
    brandLabel: "ProNeurs trademark Personal CBP Sites home", brand: "ClickBaitPays Replicated Sites",
    navigation: "Page navigation", liveSite: "See a live site", login: "Customer login",
    headlineStart: "Supercharge your", headlineMiddle: "growth with a", headlineEnd: "replicated site",
    lead: "Your own custom growth hub—personalized with your referral link, high-impact videos, resources, and an interactive calculator visitors can use to model campaign potential.",
    signup: "Get My Replicated CBP Site", demo: "See a replicated site",
    pricing: "Subscription pricing", monthly: "Monthly", monthlyPrice: "$9", perMonth: "/month", billedMonthly: "Billed monthly",
    annual: "Annual", annualPrice: "$79", perYear: "/year", bestValue: "Best value · 27% off", savings: "Save $29 every year", secure: "Secure checkout through Stripe",
    previewLabel: "Preview of a personalized ClickBaitPays replicated site", liveExample: "Live example",
    previewImage: "/clickbaitpays-replicated-site-preview.jpg",
    previewAlt: "Personalized ClickBaitPays sponsor site with the ClickBaitPays welcome video and referral call to action",
    previewCaption: "Personalized replicated site", previewTagline: "Professional from the very first click.", openExample: "Open the replicated-site example", openSite: "Open live site", memberNote: "Made for ClickBaitPays members",
    benefitsEyebrow: "Your custom CBP growth hub.", benefitsTitle: "Power every conversation with one replicated site.",
    benefits: [
      { title: "Customized to you", copy: "Your name, contact details, and official referral link—presented professionally." },
      { title: "Marketing, ready to share", copy: "Give prospects one polished place for high-impact videos, resources, and opportunity information." },
      { title: "Built-in campaign calculator", copy: "Let visitors model 1, 2, or 3 campaigns, referral scenarios, and potential paths to full campaign capacity." },
      { title: "Built to help you grow", copy: "Share one memorable link in every text, email, post, or real-life CBP conversation." },
    ],
    closingEyebrow: "Your CBP opportunity deserves a stronger follow-up.", closingTitle: "Put your replicated site to work.",
    footer: "Independent website service for ClickBaitPays members. Not affiliated with or endorsed by ClickBaitPays.", legalLinks: "Legal links", terms: "Terms", privacy: "Privacy", refunds: "Refund policy",
  },
  fr: {
    title: "Créez votre site ClickBaitPays personnalisé",
    description: "Développez votre activité ClickBaitPays avec un site personnalisé comprenant votre lien de parrainage, des vidéos, des ressources et un calculateur interactif.",
    ogTitle: "Votre site ClickBaitPays personnalisé, prêt à être partagé.",
    ogDescription: "Un site professionnel avec votre lien de parrainage et des ressources ClickBaitPays utiles.",
    twitterTitle: "Créez votre site ClickBaitPays personnalisé.", twitterDescription: "Votre espace CBP personnalisé, prêt à partager.",
    ogImage: "/og-fr.png", ogWidth: 1536, ogHeight: 1024, ogLocale: "fr_FR",
    brandLabel: "Accueil des sites CBP personnalisés ProNeurs", brand: "Sites ClickBaitPays personnalisés",
    navigation: "Navigation de la page", liveSite: "Voir un site en direct", login: "Connexion client",
    headlineStart: "Donnez de l’élan à votre", headlineMiddle: "grâce à un", headlineEnd: "site personnalisé",
    lead: "Votre espace professionnel, personnalisé avec votre lien de parrainage, des vidéos, des ressources et un calculateur interactif que vos visiteurs peuvent utiliser pour explorer le potentiel des campagnes.",
    signup: "Créer mon site CBP personnalisé", demo: "Voir un site personnalisé",
    pricing: "Tarifs d’abonnement en dollars américains", monthly: "Mensuel", monthlyPrice: "9 $ US", perMonth: "/mois", billedMonthly: "Facturé chaque mois",
    annual: "Annuel", annualPrice: "79 $ US", perYear: "/an", bestValue: "Meilleur tarif · 27 % d’économie", savings: "Économisez 29 $ US par an", secure: "Paiement sécurisé par Stripe",
    previewLabel: "Aperçu d’un site ClickBaitPays personnalisé", liveExample: "Exemple en direct",
    previewImage: "/clickbaitpays-replicated-site-preview-fr.jpg", previewAlt: "Aperçu visuel de la mise en page du site de parrainage ClickBaitPays",
    previewCaption: "Site personnalisé", previewTagline: "Professionnel dès le premier clic.", openExample: "Ouvrir l’exemple de site personnalisé", openSite: "Ouvrir le site", memberNote: "Conçu pour les membres ClickBaitPays",
    benefitsEyebrow: "Votre espace CBP personnalisé.", benefitsTitle: "Un seul site pour donner de la force à chaque conversation.",
    benefits: [
      { title: "Personnalisé pour vous", copy: "Votre nom, vos coordonnées et votre lien de parrainage officiel, présentés de manière professionnelle." },
      { title: "Prêt à partager", copy: "Offrez à vos contacts un seul espace soigné pour les vidéos, les ressources et les informations utiles." },
      { title: "Calculateur de campagnes intégré", copy: "Vos visiteurs peuvent modéliser une, deux ou trois campagnes, des scénarios de parrainage et différents parcours." },
      { title: "Conçu pour vous aider à progresser", copy: "Partagez un lien mémorable dans vos messages, e-mails, publications et conversations ClickBaitPays." },
    ],
    closingEyebrow: "Votre opportunité CBP mérite un suivi plus convaincant.", closingTitle: "Mettez votre site personnalisé au travail.",
    footer: "Service de site web indépendant pour les membres ClickBaitPays. Ni affilié ni approuvé par ClickBaitPays.", legalLinks: "Liens juridiques", terms: "Conditions", privacy: "Confidentialité", refunds: "Remboursements",
  },
  de: {
    title: "Ihre persönliche ClickBaitPays-Website erstellen",
    description: "Bauen Sie Ihre ClickBaitPays-Aktivität mit einer persönlichen Website aus: mit Ihrem Empfehlungslink, Videos, Materialien und einem interaktiven Rechner.",
    ogTitle: "Ihre persönliche ClickBaitPays-Website – bereit zum Teilen.",
    ogDescription: "Eine professionelle Website mit Ihrem Empfehlungslink und hilfreichen ClickBaitPays-Materialien.",
    twitterTitle: "Erstellen Sie Ihre persönliche ClickBaitPays-Website.", twitterDescription: "Ihr persönlicher CBP-Auftritt – bereit zum Teilen.",
    ogImage: "/clickbaitpays-replicated-site-preview-de.jpg", ogWidth: 1674, ogHeight: 714, ogLocale: "de_DE",
    brandLabel: "Startseite der persönlichen CBP-Websites von ProNeurs", brand: "Persönliche ClickBaitPays-Websites",
    navigation: "Seitennavigation", liveSite: "Live-Beispiel ansehen", login: "Kundenlogin",
    headlineStart: "Stärken Sie Ihre", headlineMiddle: "Aktivität mit einer", headlineEnd: "persönlichen Website",
    lead: "Ihr eigener professioneller Webauftritt – mit Ihrem Empfehlungslink, aussagekräftigen Videos, Materialien und einem interaktiven Rechner, mit dem Besucher das Potenzial von Kampagnen durchspielen können.",
    signup: "Meine persönliche CBP-Website erstellen", demo: "Persönliche Website ansehen",
    pricing: "Abonnementpreise in US-Dollar", monthly: "Monatlich", monthlyPrice: "9 US$", perMonth: "/Monat", billedMonthly: "Monatliche Abrechnung",
    annual: "Jährlich", annualPrice: "79 US$", perYear: "/Jahr", bestValue: "Bester Preis · 27 % sparen", savings: "Sparen Sie 29 US$ pro Jahr", secure: "Sichere Zahlung über Stripe · Preise in US-Dollar",
    previewLabel: "Vorschau einer persönlichen ClickBaitPays-Website", liveExample: "Live-Beispiel",
    previewImage: "/clickbaitpays-replicated-site-preview-de.jpg", previewAlt: "Persönliche ClickBaitPays-Website mit Begrüßungsvideo und Empfehlungslink",
    previewCaption: "Persönliche Website", previewTagline: "Professionell vom ersten Klick an.", openExample: "Beispiel der persönlichen Website öffnen", openSite: "Website öffnen", memberNote: "Für ClickBaitPays-Mitglieder entwickelt",
    benefitsEyebrow: "Ihr persönlicher CBP-Webauftritt.", benefitsTitle: "Eine Website, die jedes Gespräch weiterbringt.",
    benefits: [
      { title: "Auf Sie zugeschnitten", copy: "Ihr Name, Ihre Kontaktdaten und Ihr offizieller Empfehlungslink – professionell präsentiert." },
      { title: "Bereit zum Teilen", copy: "Bieten Sie Interessenten einen übersichtlichen Ort für aussagekräftige Videos, Materialien und Informationen zur Geschäftsmöglichkeit." },
      { title: "Integrierter Kampagnenrechner", copy: "Besucher können eine, zwei oder drei Kampagnen, Empfehlungsszenarien und mögliche Wege zur vollen Kampagnenkapazität durchspielen." },
      { title: "Für Ihr Wachstum entwickelt", copy: "Teilen Sie einen einprägsamen Link in Nachrichten, E-Mails, Beiträgen und persönlichen CBP-Gesprächen." },
    ],
    closingEyebrow: "Bleiben Sie mit Ihren CBP-Interessenten wirkungsvoll in Kontakt.", closingTitle: "Machen Sie mehr aus Ihrer persönlichen Website.",
    footer: "Unabhängiger Website-Service für ClickBaitPays-Mitglieder. Nicht mit ClickBaitPays verbunden oder von ClickBaitPays unterstützt.", legalLinks: "Rechtliche Informationen", terms: "Bedingungen", privacy: "Datenschutz", refunds: "Erstattungen",
  },
} satisfies Record<SiteLocale, object>;
